[package]
name = "tarea"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
rusqlite = "0.31"
chrono = { version = "0.4", features = ["serde"] }
colored = "3.0.0"
