name: Git Cliff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit
        run: |
          git checkout ${{ github.ref_name }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          RANGE="${{ github.event.before }}..${{ github.sha }}"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RANGE="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
          fi
          COMMITS=$(git log --format=%h $RANGE | paste -sd "," -)
          git commit -m "Update changelog" -m "$COMMITS"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ${{ github.ref_name }}

      - name: Write changelog diff to summary
        run: |
          echo "## ⮞ Changelog Diff" >> $GITHUB_STEP_SUMMARY
          git diff HEAD~1 HEAD -- CHANGELOG.md >> $GITHUB_STEP_SUMMARY || true

